# Evaluation file

### Uses the exported results from the artifacts folder
to avoid rerunning entire notebooks

In [3]:
from pathlib import Path
import pandas as pd
import numpy as np
import re

ART = Path("../artifacts/artifacts_raiders")

from utils.artifacts import load_artifacts
from utils.evaluation import (
    candidate_survival_rates,
    check_raw_occurrences,
    count_posts_with_term,
    extract_vocabulary,
    failure_stage,
    gram_to_string,
    identify_failure_stages,
    recover_vocabularies,
    track_terms,
)

(
    data,
    tfidf_candidates,
    candidate_scores,
    candidate_post_scores,
    candidate_metadata,
    anchor_metadata,
) = load_artifacts(ART)

### Define known expressions

cf Table IV of Kikkisetti et al. (2024)

In [4]:
known_terms = [
    "white genocide",
    "deep state",
    "interest groups",
    "kazarian mafia",
]

new_terms = [
    "fema camps",
    "klaus schwab",
    "central bank",
    "national socialist",
]

false_positives = [
    "plain sight",
    "german people",
    "new york city",
    "big part",
]

gold = pd.DataFrame({
    "term": known_terms + new_terms + false_positives,
    "label": (
        ["known"] * len(known_terms)
        + ["new"] * len(new_terms)
        + ["negative"] * len(false_positives)
    ),
})

display(gold)

                  term     label
0       white genocide     known
1           deep state     known
2      interest groups     known
3       kazarian mafia     known
4           fema camps       new
5         klaus schwab       new
6         central bank       new
7   national socialist       new
8          plain sight  negative
9        german people  negative
10       new york city  negative
11            big part  negative

In [8]:
ranking = candidate_scores.sort_values(
    "relevance", ascending=False
).reset_index(drop=True)

display(ranking.head(50))

                        candidate  relevance
0                       holocaust   0.866271
1   holocaust christian holocaust   0.859916
2              holocaust happened   0.845704
3                            kike   0.832530
4               germany holocaust   0.832016
5           generations holocaust   0.828941
6                        lolohoax   0.827880
7             holocaust narrative   0.824386
8                        kike god   0.823677
9                      kike lover   0.822876
10                 jews holocaust   0.822364
11             accounts holocaust   0.821807
12             holocaust real gas   0.821388
13               jewish holocaust   0.820218
14                     david kike   0.819559
15                 something kike   0.818170
16                    kike insult   0.817881
17                       kike guy   0.816532
18                    soviet kike   0.815556
19              holocaust victims   0.814611
20                     kike kikes   0.814568
21             holocaust survivor   0.814102
22                     thing kike   0.813821
23                       cum kike   0.813578
24            holocaust survivors   0.813281
25                    kike tricks   0.813234
26               kike kike matter   0.813173
27                  politics kike   0.812318
28                         kike k   0.812282
29                      dumb kike   0.812277
30              history holocaust   0.811049
31              revenge holocaust   0.810922
32                kike propaganda   0.810844
33                  kike salty af   0.810451
34                      rich kike   0.809884
35                fuck kike kikes   0.809737
36                kike conspiracy   0.809510
37                 shame holohoax   0.809395
38                     kike alert   0.809148
39                 holocaust myth   0.809087
40                   kike marxist   0.808988
41                     kike thing   0.808848
42                   kike someone   0.808467
43                     kike child   0.808308
44                      kike shit   0.807727
45            lolohoax importance   0.807678
46                      kike wars   0.807620
47                   problem kike   0.807502
48                       ike kike   0.807152
49                    kike buckle   0.807044

In [9]:
ranking_counts = pd.read_csv(
    ART / "ranked_candidates_with_counts.csv",
    keep_default_na=False,
)

display(ranking_counts.head(50))

                        candidate  relevance  n_posts  n_occurrences
0                       holocaust   0.866271      287            349
1   holocaust christian holocaust   0.859916        1              1
2              holocaust happened   0.845704        1              1
3                            kike   0.832530      501            520
4               germany holocaust   0.832016        1              1
5           generations holocaust   0.828941        2              2
6                        lolohoax   0.827880        1              1
7             holocaust narrative   0.824386        2              2
8                        kike god   0.823677        1              1
9                      kike lover   0.822876        3              3
10                 jews holocaust   0.822364        3              3
11             accounts holocaust   0.821807        1              1
12             holocaust real gas   0.821388        1              1
13               jewish holocaust   0.820218        1              1
14                     david kike   0.819559        1              1
15                 something kike   0.818170        1              1
16                    kike insult   0.817881        1              1
17                       kike guy   0.816532        1              1
18                    soviet kike   0.815556        1              1
19              holocaust victims   0.814611        3              3
20                     kike kikes   0.814568        2              2
21             holocaust survivor   0.814102        2              2
22                     thing kike   0.813821        1              1
23                       cum kike   0.813578        1              1
24            holocaust survivors   0.813281        2              2
25                    kike tricks   0.813234        1              1
26               kike kike matter   0.813173        1              1
27                  politics kike   0.812318        1              1
28                         kike k   0.812282        1              1
29                      dumb kike   0.812277        3              3
30              history holocaust   0.811049        2              2
31              revenge holocaust   0.810922        1              1
32                kike propaganda   0.810844        5              5
33                  kike salty af   0.810451        1              1
34                      rich kike   0.809884        1              1
35                fuck kike kikes   0.809737        1              1
36                kike conspiracy   0.809510        1              1
37                 shame holohoax   0.809395        1              1
38                     kike alert   0.809148        1              1
39                 holocaust myth   0.809087        1              1
40                   kike marxist   0.808988        1              1
41                     kike thing   0.808848        1              1
42                   kike someone   0.808467        1              1
43                     kike child   0.808308        1              1
44                      kike shit   0.807727        1              1
45            lolohoax importance   0.807678        1              1
46                      kike wars   0.807620        1              1
47                   problem kike   0.807502        1              1
48                       ike kike   0.807152        1              1
49                    kike buckle   0.807044        1              1

### recover the vocabulary at each stage

In [5]:
(
    vocab_before_pos,
    vocab_after_pos,
    vocab_after_tfidf,
    vocab_scored,
) = recover_vocabularies(data, tfidf_candidates, candidate_scores)

Before POS: 51801
After POS: 11587
After TF-IDF: 4661
Scored candidates: 4661

#### Check if expression exists in the raw corpus

In [6]:
gold = check_raw_occurrences(gold, data)

display(gold)

                  term     label  raw_posts  in_raw
0       white genocide     known          2    True
1           deep state     known          0   False
2      interest groups     known          0   False
3       kazarian mafia     known          0   False
4           fema camps       new          0   False
5         klaus schwab       new          0   False
6         central bank       new          2    True
7   national socialist       new          1    True
8          plain sight  negative          0   False
9        german people  negative          1    True
10       new york city  negative          0   False
11            big part  negative          0   False

### trace every expression through the pipeline

In [7]:
(
    gold,
    ranking,
    rank_lookup,
    score_lookup,
    threshold,
) = track_terms(
    gold, vocab_before_pos, vocab_after_pos, vocab_after_tfidf,
    vocab_scored, candidate_scores,
)

display(gold)

,term,label,raw_posts,in_raw,generated,after_pos,after_tfidf,scored,rank,relevance,passes_hmapp
0,white genocide,known,2,True,True,True,False,False,NaN,NaN,False
1,deep state,known,0,False,False,False,False,False,NaN,NaN,False
2,interest groups,known,0,False,False,False,False,False,NaN,NaN,False
3,kazarian mafia,known,0,False,False,False,False,False,NaN,NaN,False
4,fema camps,new,0,False,False,False,False,False,NaN,NaN,False
5,klaus schwab,new,0,False,False,False,False,False,NaN,NaN,False
6,central bank,new,2,True,True,True,True,True,3322.0,0.47462,False
7,national socialist,new,1,True,True,True,False,False,NaN,NaN,False
8,plain sight,negative,0,False,False,False,False,False,NaN,NaN,False
9,german people,negative,1,True,True,True,False,False,NaN,NaN,False
10,new york city,negative,0,False,False,False,False,False,NaN,NaN,False
11,big part,negative,0,False,False,False,False,False,NaN,NaN,False

### identify the failure stage

In [ ]:
gold = identify_failure_stages(gold)

display(
    gold[[
        "term",
        "label",
        "raw_posts",
        "outcome",
        "rank",
        "relevance",
    ]]
)

,term,label,raw_posts,outcome,rank,relevance
0,white genocide,known,5,Retained by HMApp,791.0,0.617182
1,deep state,known,12,Retained by HMApp,2967.0,0.533629
2,interest groups,known,3,Semantic relevance cutoff,4966.0,0.483584
3,kazarian mafia,known,0,Absent from raw corpus,NaN,NaN
4,fema camps,new,2,Retained by HMApp,2881.0,0.536202
5,klaus schwab,new,9,Semantic relevance cutoff,4715.0,0.489486
6,central bank,new,3,Semantic relevance cutoff,6504.0,0.442916
7,national socialist,new,3,TF-IDF filtering,NaN,NaN
8,plain sight,negative,4,Semantic relevance cutoff,6210.0,0.451854
9,german people,negative,5,Retained by HMApp,1480.0,0.582787
10,new york city,negative,4,Retained by HMApp,3363.0,0.522923
11,big part,negative,4,Semantic relevance cutoff,6117.0,0.454143

## Eval metrics

### Candidate-stage recall

In [ ]:
positives = gold.loc[
    gold["label"].isin(["known", "new"])
    & gold["in_raw"]
]

stages = [
    "generated",
    "after_pos",
    "after_tfidf",
    "scored",
    "passes_hmapp",
]

survival_rates = candidate_survival_rates(positives, stages)

for stage, rate in survival_rates.items():
    print(f"{stage}: {rate:.1%}")

generated: 100.0%
after_pos: 100.0%
after_tfidf: 85.7%
scored: 85.7%
passes_hmapp: 42.9%

### Ranking quality

In [ ]:
display(
    gold.loc[
        gold["label"].isin(["known", "new"]),
        ["term", "rank", "relevance"]
    ].sort_values("rank")
)

                 term    rank  relevance
0      white genocide   791.0   0.617182
4          fema camps  2881.0   0.536202
1          deep state  2967.0   0.533629
5        klaus schwab  4715.0   0.489486
2     interest groups  4966.0   0.483584
6        central bank  6504.0   0.442916
3      kazarian mafia     NaN        NaN
7  national socialist     NaN        NaN